"""add expiration_time to auth table

Revision ID: 3dd6c8e934e0
Revises: c8c727b8b796
Create Date: 2024-06-19 15:22:13.323893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd6c8e934e0'
down_revision: Union[str, None] = 'c8c727b8b796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('expiration_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'expiration_time')
    # ### end Alembic commands ###
