"""add ref_link, balance to User and sale_price to divnatnations

Revision ID: 571cc70b428f
Revises: 303d5fe9e05f
Create Date: 2024-06-24 14:33:46.967502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571cc70b428f'
down_revision: Union[str, None] = '303d5fe9e05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divinations', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('referal_link', sa.String(), nullable=True))
    op.add_column('user', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'balance')
    op.drop_column('user', 'referal_link')
    op.drop_column('divinations', 'sale_price')
    # ### end Alembic commands ###
