"""add comment to divinations

Revision ID: 7f1b8635d41e
Revises: 8890679bafcd
Create Date: 2024-06-13 15:13:20.840823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1b8635d41e'
down_revision: Union[str, None] = '8890679bafcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divinations', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('divinations', 'comment')
    # ### end Alembic commands ###
