"""add table positions

Revision ID: 8890679bafcd
Revises: a1ae90395392
Create Date: 2024-06-13 14:34:51.555960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8890679bafcd'
down_revision: Union[str, None] = 'a1ae90395392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'positions', 'divinations', ['div_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    # ### end Alembic commands ###
