"""add is_code_valid in models auth

Revision ID: abe4aba5eb9c
Revises: 3dd6c8e934e0
Create Date: 2024-06-19 15:28:03.395242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe4aba5eb9c'
down_revision: Union[str, None] = '3dd6c8e934e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
