"""add table reviews

Revision ID: da9fdad22baf
Revises: af89140ccbd2
Create Date: 2024-06-24 17:15:29.576036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9fdad22baf'
down_revision: Union[str, None] = 'af89140ccbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('divinations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('divinations', sa.Column('questionForThe_cards', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('divinations', 'questionForThe_cards')
    op.drop_column('divinations', 'description')
    op.drop_table('reviews')
    # ### end Alembic commands ###
